### ISSUE TITLE
Spelling error (and also different name)

### ISSUE THREAD

**Issue by marijneken** [hardillb/node-red-contrib-googlehome#1]
When dragging the "google home" node into a flow, it's default name appears as "Goolge Assistant". With that spelling mistake. But also, it's called "home" in the node list but "Assistant" in the flow.
I think Google Home is the correct name. Google Assistant is just another app that can issue Google Home commands.
![image](https://user-images.githubusercontent.com/928998/51090839-a1d83800-1782-11e9-8cb7-4571d29747dc.png)

**Comment by hardillb** [comment]
OK, typo fixed, but it's going to stay as "Google Assistant" as actions are for Google Assistant, not just Google Home devices.
