### ISSUE TITLE
site and service down ?? 

### ISSUE THREAD

**Issue by N0NameN0** [hardillb/node-red-contrib-googlehome#12]
Node-RED Google Assistant Smart Home Skill Bridge
It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one.

**Comment by N0NameN0** [comment]
BTW is there a way i host my own service to avoid this situation ? ;)

**Comment by hardillb** [comment]
Service is back up, I had to temperately ban some people doing bad things.

And while yes you can run it yourself I will not be supplying instructions on how, if you can work it out then fine.

**Comment by N0NameN0** [comment]
thx.
Hope you will open source / open doc this magic part one day... at least when you will decide to stop to host it for us ;)
thx again.
