### ISSUE TITLE
Fan speed trait doesn't work

### ISSUE THREAD

**Issue by ninjakatze** [hardillb/node-red-contrib-googlehome#13]
Unfortunately the fan speed trait doesn't get recognized by the google home graph. Although the setting has been set in the webUI the google home app gives me only the options to turn on / turn off the fan but no option for setting the actual fan speed. Same applies for the purifier. Can you investigate if anything has changed on API side?

**Comment by hardillb** [comment]
Is this in the GUI or via voice?

**Comment by hardillb** [comment]
The following link explains what traits are supported on what devices for UI components to control them.
https://developers.google.com/assistant/smarthome/develop/touch-controls

Fan speed is only supported on devices like the Nest Hub, not on the phone apps
