### ISSUE TITLE
Non working device types

### ISSUE THREAD

**Issue by Marty56** [hardillb/node-red-contrib-googlehome#14]
Is this node still worked on, if yes please correct the following device types

1. Door, Sensor: displaying wrong symbol in Google Home app and also has no function in Home App

2. Thermostat: In Google home App, if you turn heating off, and return to turn heating on, heating is already selected, therefore if you press on heating a second it does not send a command to node red. 
Also documentation is missing. E.g. how to access the actual temperature.

**Comment by hardillb** [comment]
1. Not all device types are supported in the Google Hone App, This is for Google to fix The list of supported devices on which types of display is here: https://developers.google.com/assistant/smarthome/develop/touch-controls
 2. Again this is an artefact of the Google Home app and as such Google's problem not something I can solve.

As for the doc you will have to be clearer on what you mean. How to access what temperature from where?

**Comment by Marty56** [comment]
Thanks for the fast feedback.

In the thermostat in the google home app I see the actual temperature of the room.
I would like to change this temperature based on the temperature measured by my real thermostat. So I need to send a command to the "virtual" thermostat to change the value.

**Comment by Marty56** [comment]
With respect to Door and Sensor, I do not see a way to used these devices. With the given functionality they are useless.
 I would recommend to remove them in the "device" web page until they have a function

**Comment by hardillb** [comment]
That is already in the doc.

click on the word "TemperatureSetting" Just above "Sending a Resoponse". The last example in the list shows what to send into a response node to update the current temperature reading.

The Door and Sensor devices work just fine if you interact with them via voice and are used by many existing users, they will not be removed.

**Comment by hardillb** [comment]
Be sure to only update the ambient temperature when it changes, the best way is to include a RBE node between the input and the response node.

**Comment by Marty56** [comment]
to my understanding "TemperatureSetting" sets the desired temperature of thermostat. What I was asking for how to set the "ambient Temperature", so that this Temperature is correctly displayed in the google home app.

**Comment by hardillb** [comment]
Asked and answered, read what I said.

> The last example in the list shows what to send into a response node to update the current temperature reading.

**Comment by Marty56** [comment]
![Bildschirmfoto 2021-03-07 um 08 58 50](https://user-images.githubusercontent.com/8623789/110233367-cd4eab80-7f23-11eb-8569-bd9f62feefed.jpeg)

**Comment by hardillb** [comment]
yes, already answered

**Comment by Marty56** [comment]
Ok. 
I am using 
as path: payload.params.TemperatureSetting
type:string??

**Comment by hardillb** [comment]
Do as I said. Click on "TemperatureSetting" in the doc, it expands to show examples. The last example is the format you need.

**Comment by Marty56** [comment]
OK. I give up. Maybe the documentation is perfect but I am just to stupid.

**Comment by Marty56** [comment]
I discovered "(click on trait name to expand):"
Unfortunately the documentation was hidden behind a link that was not displayed properly.

It is working now!
