### ISSUE TITLE
knock knock !! 

### ISSUE THREAD

**Issue by N0NameN0** [hardillb/node-red-contrib-googlehome#18]
down ?? ;)

**Comment by hardillb** [comment]
From #google-home on Slack:

> It looks like there are a few users pushing status/sensor updates when nothing has changed too quickly again which is causing excessive load on the back end of the NR-GAB system. I am away at the moment so don't have time to do the log analysis to work out exactly who and ask them to stop. If the service is still impacted Sunday night when I get back I will chase them down.

**Comment by N0NameN0** [comment]
we perhaps need a "small fee" registering annual account to get ride of some of them ?? ;=)

**Comment by hardillb** [comment]
I've managed to find a quiet 20mins to disable a few accounts and the load levels look better.

So I'm going to close this for now.

**Comment by N0NameN0** [comment]
> I've managed to find a quiet 20mins to disable a few accounts and the load levels look better.
> 
> So I'm going to close this for now.

we love you ;) <3
