### ISSUE TITLE
Node properties reset upon refresh or re-open

### ISSUE THREAD

**Issue by marijneken** [hardillb/node-red-contrib-googlehome#2]
When using the google-home node, the Device seems to reset (to the top one in the list?) when you re-open the node. Also, when clicking the refresh button, after the refresh, the Device is reset to the first one in the list.
Actually, when opening the node and quickly changing the device (within a second), I noticed the Device would actually "jump back" to the first item by itself, after another second or so.

**Comment by hardillb** [comment]
fixed by https://github.com/hardillb/node-red-contrib-googlehome/commit/d79718d6696b4b8e0bc3f6c2de006e0300100608

Updated npm package here https://www.hardill.me.uk/node-red-contrib-googlehome-0.0.3.tgz
