### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by william89731** [hardillb/node-red-contrib-googlehome#24]
![image](https://user-images.githubusercontent.com/68069659/221926472-b295c637-0051-4519-9c7a-c4444b364ce5.png)

It's been more than two years since the last update.

**Comment by hardillb** [comment]
Because there has been no need for any updates

**Comment by william89731** [comment]
request  has been deprecated.
bump latest mqtt

**Comment by hardillb** [comment]
Feel free to submit a compelling argument as to why they need to be updated along with your tested PR and I'll consider it, but this is a closed environment the nodes only talk to one place, there are no pressing reasons to change it so far.
