### ISSUE TITLE
The node is down

### ISSUE THREAD

**Issue by azxo1** [hardillb/node-red-contrib-googlehome#25]
Regards! Yesterday I reported that https://googlehome.hardill.me.uk/ was unavailable. I was wrong, I can access it using mobile internet, but not from my home internet. I've already checked my mikrotik firewall, but I can't find a block for their server. Could it be that your (hardill) server blocked me? Because, of course, that's not how my Google Assistant works in node-red. Thank you very much for your answer! (no changes were made in google assistant and node red) (sorry, poor English)

**Comment by hardillb** [comment]
No, the service will not block like that (Accounts get disabled for users that abuse the service, but not IP level blocking).

Assuming you are having problems from both a web browser and Node-RED on the same machine on your LAN then the only thing I can suggest is that you may have a broken IPv6 configuration.

If that is not the problem then you'll have to talk to your ISP.

**Comment by azxo1** [comment]
Everything works perfectly, I can access everything (node ​​red, printer and many others), only the server https://googlehome.hardill.me.uk/ cannot be reached. IPv6 is turned off, I didn't even use it. So nothing was changed, suddenly the google assistant didn't work. I would be so sorry if this didn't work because it is the most perfect assistant bridge! Very nice job!

**Comment by hardillb** [comment]
This is not a problem with the service, it will be something in your environment

You haven't shared any information (apart from the fact it works from your phone) about what you've tried to debug this.

I suggest you check the following:

- Can you resolve `googlehome.hardill.me.uk` to a IP address, if so what address?
- Can you connect to `https://googlehome.me.uk` using a tool like curl?
- Exactly what error messages are you getting when you try and connect?
- Have you asked your ISP if there are any problems with their service?

**Comment by azxo1** [comment]
DNS_PROBE_FINISHED_NXDOMAIN
I don't have any other internet connection issues. I can't access this page alone.

**Comment by hardillb** [comment]
Assuming you are on windows (because you really are not helping me help you here)

Run `nslookup googlehome.hardill.me.uk`

If that doesn't return valid IP addresses then your DNS setup is broken (or most likely your ISPs) and you will have to talk to them about the problem. This is not something I can fix.

**Comment by azxo1** [comment]
Sorry, language difficulties. I don't mean to be disrespectful. Yes, I use windows, but I can't access the server from my own network, whether it's an android phone or a winows OS PC. I did not find any errors in my Mikrotik firewall, if this error was only on the Windows PC, then it could be ESET Smart antivirus or Windows Defender, but the phenomenon can also be experienced on Android phones, in any browser (firefox, chrome, edge). I have already restarted everything, a DNS error is unlikely, because I can access all websites (external and internal IP), everything works, only https://googlehome.hardill.me.uk/ does not work. That's why I thought your server might have banned me. I access their server from mobile internet, so it works fine. Thank you very much for your efforts! (I understand network stuff quite well, ((not professional level, but good)) but now I don't understand this)

**Comment by hardillb** [comment]
The error message you gave DNS_PROBE_FINISHED_NXDOMAIN implies that your browser (chrome?) could not turn the host name into a IP address, hence why I asked you to run the nslookup command (which you have not done) to test this.

If you are not going to do the things I ask there is no point in continuing this.

As I've said, there is no problem with the service it's self, this is problem that is either local to your network or your ISP and not something I can help with.

**Comment by azxo1** [comment]
Sorry, I forgot to attach it
`C:\Users\Apa>nslookup googlehome.hardill.me.uk
Server:  UnKnown
Address:  192.168.41.45

Non-authoritative answer:
Name:    googlehome.hardill.me.uk
Addresses:  2a05:d018:8c4:3201:2a72:eccf:e8a:2b76
          34.241.226.122`

IP not blocking

**Comment by hardillb** [comment]
OK, so it's returned the right addresses so that just leaves what ever other services you have installed that might be stopping the browser opening the page.

Browsers these days may be using DNS over HTTPS so it's a totally definitive test, but  I'm out of ideas now.

**Comment by azxo1** [comment]
I also ran out, that's why I turned to you. I don't know why, the assistant stopped working for no reason at all. And it is incomprehensible that only https://googlehome.hardill.me.uk/ is not accessible from my own network. I couldn't find a reason for it, neither in the firewall nor elsewhere... But thank you very much anyway!!!
(I once had a similar, rented hosting with wordpress, paid template, 1 bad plugin and BitNinja blocked the IP address of the rented server, so my website became unreachable until the hosting provider fixed it. Isn't a similar problem possible?)

**Comment by azxo1** [comment]
Well, serve as a lesson to everyone who makes such a mistake. Because even though I checked my mikrotik firewall 20 times, I still had the error. There is not much information on the internet about protocolless ip ban. But it's simple: /ip firewall raw add action=drop chain=prerouting disabled=yes dst-address=34.241.226.122 \
    protocol=tcp
Well, I didn't notice that, deleting it immediately solved my problem. Once again, thank you very much! And it really is the best, easiest google assistant bridge!
