### ISSUE TITLE
This node is down

### ISSUE THREAD

**Issue by azxo1** [hardillb/node-red-contrib-googlehome#26]
Everything works perfectly, I can access everything (node ​​red, printer and many others), only the server https://googlehome.hardill.me.uk/ cannot be reached. IPv6 is turned off, I didn't even use it. So nothing was changed, suddenly the google assistant didn't work. I would be so sorry if this didn't work because it is the most perfect assistant bridge! Very nice job!

**Comment by hardillb** [comment]
Please do not open new issues

**Comment by azxo1** [comment]
You just closed the question.
