### ISSUE TITLE
device propery is not populated

### ISSUE THREAD

**Issue by hansj10** [hardillb/node-red-contrib-googlehome#29]
Hi Hardillb,
the device properties of the google home node are not populated anymore. The refresh button does not work. 
NR debug log does not show an error related to the google bridge.
My username is "hansj". 
I did add a new device on the web portal first, then noticed that I can not use the google nodes anymore as the device information is not there.
Creating a new google home node and assigning the account, the device property is also not updated.

Thanks for your help!
hansj

**Comment by hardillb** [comment]
Please share the output of the following command

```
curl "https://username:password@googlehome.hardill.me.uk/user/api/devices"
```

Make sure to swap the `username:password` for your username and password from the service

**Comment by hansj10** [comment]
my password did contain special characters that the api logon does not like. After choosing an easier password everything works fine. Thanks!

**Comment by hansj10** [comment]
password complexity caused api logon issues.
