### ISSUE TITLE
[Question] Is the project still under development?

### ISSUE THREAD

**Issue by FernandoWahl** [hardillb/node-red-contrib-googlehome#4]
I used your project when you had an "Alexa". I migrated to google home and saw that the project is not available.

<img width="865" alt="Captura de Tela 2019-11-25 às 21 36 03" src="https://user-images.githubusercontent.com/7410060/69589796-fa47ab00-0fcb-11ea-826b-cf89a421f516.png">

I tried to deploy and configure the base project on my server but without success. (https://github.com/hardillb/node-red-contrib-googlehome-web)
Could you help me with the basics of how to set it up?

Thank you

**Comment by hardillb** [comment]
Yes, it's still being worked on, I'm now blocked by Google's SDK for local control not supporting hub style devices.

I am trying to find time to get the service as it is approved and released, as it says in BIG RED LETTERS you need to be patient.

No, I will not be supplying any instructions about how to run your own version of the service
