### ISSUE TITLE
Can we sign up to be notified when the beta is open?

### ISSUE THREAD

**Issue by bwims** [hardillb/node-red-contrib-googlehome#5]
Hi,

would it be possible to submit our email addresses to know when the beta is open to new users?

Failing that, is there a ball park idea of when would be a good time to investigate again?

Many thanks!

**Comment by hardillb** [comment]
I will make an announcement in #googe-home-assistant on the Node-RED Slack when it has been approved.

If you have already created an account I will also send an email to the address supplied with instructions when it's ready.

I submit the service for approval last week and I have been in contact with Google about it yesterday, so I hope it will be soon.
