### ISSUE TITLE
Support 'device selection' based on roomHint.

### ISSUE THREAD

**Issue by gvdhoven** [hardillb/node-red-contrib-googlehome#8]
With Christmas around the corner, I would like to use multiple Switches called 'Christmas lights' in my house. For example, in my living room, in my garden etc. I grouped them in their own rooms, but the device selection in Node-red shows no sign in which room they are located in.

**The following code replaced in `googlehome.html` fixes that:**

> Please note; the method `getDevs` is found on 2(!) places in the googlehome.html

```
      var getDevs = function (account){
        $.getJSON('google-home/devices/' + account, function(data){
          console.log("getDevs");
          console.log(data);

          // Split device response to rooms (in case you have e.g. multiple "Christmass lights", one in "Garden" and one in "Living room"
          var rooms = { 'No roomhint assigned': [] };
          for (d in data) {
            var roomHint = (data[d].roomHint || '').trim();
            if (roomHint == '') {
              roomHint = 'No roomhint assigned';
            }
            if (!rooms.hasOwnProperty(roomHint)) {
              rooms[roomHint] = [];
            }
            rooms[roomHint].push(data[d]);
          }

          // Add all rooms and devices to the list
          $('#node-input-device').empty();
          Object.keys(rooms).sort().forEach(function(key) {
            let group = $('<optgroup label="' + key + '" />');
            for (d in rooms[key]) {
              group.append($('<option/>',{
                value: parseInt(rooms[key][d].id),
                text: rooms[key][d].name.name
              }));
            }
            if (rooms[key].length) {
            	$('#node-input-device').append(group);
            }
          });

          if (node.device) {
            $('#node-input-device').val(node.device);
          }
        })
      }
```

Sample output on my locally patched version:
![image](https://user-images.githubusercontent.com/186093/101347302-29a12100-388a-11eb-9aa6-9e3aee8062ec.png)

**Comment by hardillb** [comment]
Thanks, I'll have a proper look at the weekend when I have some time.

**Comment by gvdhoven** [comment]
Hey @hardillb , thank you for merging it. 

However, I see you left this part in the code (on 2 places):
```
$('#node-input-device').find('option').remove().end();
$('#node-input-device').val("");
```
Would this also remove the created optgroups?

I replaced that part with this code in my PR (which i off course tested):
```
$('#node-input-device').empty().val('');
```

**Comment by hardillb** [comment]
You didn't submit a pull request (or at least I can't see it)

**Comment by gvdhoven** [comment]
oh oops, you are right :) I only pasted my addition for grouping the rooms and devices.
Let me branch and create a PR for you.
